package com.tms.model;

public enum Designation {

    SR_FRONTEND_DEVELOPER,
    MID_FRONTEND_DEVELOPER,
    JR_FRONTEND_DEVELOPER,
    JR_BACKEND_DEVELOPER,
    MID_BACKEND_DEVELOPER,
    SR_BACKEND_DEVELOPER,
    CTO,
    IT_HEAD,
    PROJECT_MANAGER,
    FINANCE_MANAGER,
    JR_FINANCE_MANAGER,




}
